---
apiVersion: v1
kind: Service
metadata:
  name: map-api-test
  labels:
    app: map-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: map-api-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: map-api-deployment-dev
  labels:
    app: map-api
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: map-api-dev
    spec:
      containers:
        - image: edsonbelemancora/map-api:3.0
          imagePullPolicy: Always
          name: map-api
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-url
                  key: MONGODB_URL
          ports:
            - containerPort: 8181
